AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Select whether to create secrets, or use existing secrets
        Parameters:
          - ValuesOrArns
      - Label:
          default: AWS IAM Identity Center (Successor to AWS Single Sign-On)
        Parameters:
          - SCIMEndpointUrl
          - SCIMEndpointAccessToken
          - Region
          - IdentityStoreID
      - Label:
          default: Google Workspace Credentials 
        Parameters:
          - GoogleAdminEmail
          - GoogleCredentials
      - Label:
          default: Sync Configuration
        Parameters:
          - SyncMethod
          - GoogleUserMatch
          - GoogleGroupMatch
          - IgnoreUsers
          - IgnoreGroups
      - Label:
          default: "Configuration options for users_groups Mode only"
        Parameters:
          - IncludeGroups
      - Label:
          default: "Lambda Configuration"
        Parameters:
          - FunctionName
          - LogLevel
          - LogFormat
          - TimeOut
          - ScheduleExpression

  AWS::ServerlessRepo::Application:
    Name: ssosync
    Description: Helping you populate AWS SSO directly with your Google Apps users.
    Author: Sebastian Doell
    SpdxLicenseId: Apache-2.0
    # paths are relative to .aws-sam/build directory
    LicenseUrl: LICENSE
    ReadmeUrl: SAR.md
    Labels: [serverless, sso, lambda, scim]
    HomePageUrl: https://github.com/awslabs/ssosync
    # Update the semantic version and run sam publish to publish a new version of your app
    SemanticVersion: 1.0.0-rc.10
    # best practice is to use git tags for each release and link to the version tag as your source code URL
    SourceCodeUrl: https://github.com/awslabs/ssosync/tree/1.0.0-rc.10

Parameters:
  ValuesOrArns:
    Type: String
    Description: Decide whether to provide values for the secrets or an arn for an existing secret, that contains the value.
    AllowedValues:
      - secrets
      - values
    Default: values
  FunctionName:
    Type: String
    Description: Specify the Function you want to us for this deployment, leave empty for default behaviour.
    AllowedPattern: '(?!.*\s)|[a-zA-Z0-9-_]{1,140}'
  ScheduleExpression:
    Type: String
    Description: Schedule for trigger the execution of ssosync (see CloudWatch schedule expressions)
    Default: rate(15 minutes)
    AllowedPattern: '(?!.*\s)|rate\(\d{1,3} (minutes|hours|days)\)|(cron\((([0-9]|[1-5][0-9]|60)|\d\/([0-9]|[1-5][0-9]|60)|\*) (([0-9]|[1][0-9]|[2][0-3])|(\d\/([0-9]|[1][0-9]|[2][0-3]))|(([0-9]|[1][0-9]|[2][0-3])-([0-9]|[1][0-9]|[2][0-3]))|\*) (([1-9]|[1-2][0-9]|[3][0-1])|\d\/([1-9]|[1-2][0-9]|[3][0-1])|[1-5]W|L|\*|\?) (([1-9]|[1][1-2])|(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)|((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV)-(FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))|(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV)(,(FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)){0,11}|\d\/([0-9]|[1][0-2])|\?|\*) ((MON|TUE|WED|THU|FRI|SAT|SUN)|(MON|TUE|WED|THU|FRI|SAT)-(TUE|WED|THU|FRI|SAT|SUN)|(MON|TUE|WED|THU|FRI|SAT)(,(TUE|WED|THU|FRI|SAT|SUN)){0,6}|[1-7]L|[1-7]#[1-5]|\?|\*) ((19[7-9][0-9]|2[0-1]\d\d)|(19[7-9][0-9]|2[0-1]\d\d)-(19[7-9][0-9]|2[0-1]\d\d)|(19[7-9][0-9]|2[0-1]\d\d)(,(19[7-9][0-9]|2[0-1]\d\d))*|\*)\))'
  LogLevel:
    Type: String
    Description: Log level for Lambda function logging
    Default: warn
    AllowedValues:
      - panic
      - fatal
      - error
      - warn
      - info
      - debug
      - trace
  LogFormat:
    Type: String
    Description: Log format for Lambda function logging
    Default: json
    AllowedValues:
      - json
      - text
  TimeOut:
    Type: Number
    Description: Timeout for the Lambda function
    Default: 300
    MinValue: 1
    MaxValue: 900

  GoogleCredentials:
    Type: String
    Description: Credentials to log into Google (content of credentials.json)
    AllowedPattern: '({(\s)*(".*")(\s)*:(\s)*(".*")(\s)*})|(arn:aws:secretsmanager:us-east-2:[0-9]{8,12}:secret:[a-zA-Z0-9/_+=.@-]{1,512})'
    NoEcho: true
  GoogleAdminEmail:
    Type: String
    Description: Google Admin email
    AllowedPattern: '(([a-zA-Z0-9.+=_-]{0,61})@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*)|(arn:aws:secretsmanager:us-east-2:[0-9]{8,12}:secret:[a-zA-Z0-9/_+=.@-]{1,512})'
    NoEcho: true
  SCIMEndpointUrl:
    Type: String
    Description: AWS IAM Identity Center - SCIM Endpoint Url
    NoEcho: true
    AllowedPattern: '(https://scim.(us(-gov)?|ap|ca|cn|eu|sa)-(central|(north|south)?(east|west)?)-([0-9]{1}).amazonaws.com/(.*)-([a-z0-9]{4})-([a-z0-9]{4})-([a-z0-9]{12})/scim/v2/)|(arn:aws:secretsmanager:us-east-2:[0-9]{8,12}:secret:[a-zA-Z0-9/_+=.@-]{1,512})'
  SCIMEndpointAccessToken:
    Type: String
    Description: AWS IAM Identity Center - SCIM AccessToken
    AllowedPattern: '([0-9a-zA-Z/=+-\]{584})|(arn:aws:secretsmanager:us-east-2:[0-9]{8,12}:secret:[a-zA-Z0-9/_+=.@-]{1,512})'
    NoEcho: true
  Region:
    Type: String
    Description: AWS Region where AWS IAM Identity Center is enabled
    AllowedPattern: '(us(-gov)?|ap|ca|cn|eu|sa)-(central|(north|south)?(east|west)?)-\d|(arn:aws:secretsmanager:us-east-2:[0-9]{8,12}:secret:[a-zA-Z0-9/_+=.@-]{1,512})'
  IdentityStoreID:
    Type: String
    Description: Identifier of Identity Store in AWS IAM Identity Center
    NoEcho: true
    AllowedPattern: 'd-[1-z0-9]{10}|(arn:aws:secretsmanager:us-east-2:[0-9]{8,12}:secret:[a-zA-Z0-9/_+=.@-]{1,512})'

  GoogleUserMatch:
    Type: String
    Description: |
      Google Workspace user filter query parameter, example: 'name:John* email:admin*', see: https://developers.google.com/admin-sdk/directory/v1/guides/search-users
    Default: ""
    AllowedPattern: '(?!.*\s)|(name|Name|NAME)(:([a-zA-Z0-9]{1,64})(\*))|(name|Name|NAME)(=([a-zA-Z0-9 ]{1,64}))|(email|Email|EMAIL)(:([a-zA-Z0-9.-_]{1,64})(\*))|(email|Email|EMAIL)(=([a-zA-Z0-9.-_]{1,64})@([a-zA-Z0-9.-]{5,260}))'
  GoogleGroupMatch:
    Type: String
    Description: |
      Google Workspace group filter query parameter, example: 'name:Admin* email:aws-*', see: https://developers.google.com/admin-sdk/directory/v1/guides/search-groups
    Default: 'name:AWS*'
    AllowedPattern: '(?!.*\s)|(name|Name|NAME)(:([a-zA-Z0-9]{1,64})\*)|(name|Name|NAME)(=([a-zA-Z0-9 ]{1,64}))|(email|Email|EMAIL)(:([a-zA-Z0-9.-_]{1,64})\*)|(email|Email|EMAIL)(=([a-zA-Z0-9.-_]{1,64})@([a-zA-Z0-9.-]{5,260}))'
  IgnoreGroups:
    Type: String
    Description: |
      Ignore these Google Workspace groups, leave empty if not required
    Default: ""
    AllowedPattern: '(?!.*\s)|([0-9a-zA-Z-= _]*)(,[0-9a-zA-Z-=@. _]*)*'
  IgnoreUsers:
    Type: String
    Description: |
      Ignore these Google Workspace users, leave empty if not required
    Default: ""
    AllowedPattern: '(?!.*\s)|([0-9a-zA-Z-= _]*)(,[0-9a-zA-Z-=@. _]*)*'
  IncludeGroups:
    Type: String
    Description: |
      Include only these Google Workspace groups, leave empty if not required. (Only applicable for SyncMethod user_groups)
    Default: ""
    AllowedPattern: '(?!.*\s)|([0-9a-zA-Z-= _]*)(,[0-9a-zA-Z-=@. _]*)*'
  SyncMethod:
    Type: String
    Description: Sync method to use or whether to create just the secrets, for use with a function deployed in a separate stack
    Default: groups
    AllowedValues:
      - groups
      - users_groups
      - secrets only

Conditions:
  SetFunctionName: !Not [!Equals [!Ref "FunctionName", ""]]
  OnSchedule: !Not [!Equals [!Ref "ScheduleExpression", ""]]
  SetGoogleUserMatch: !Or [!Not [!Equals [!Ref "GoogleUserMatch", ""]], !Equals [!Ref "SyncMethod", users_groups]]
  SetGoogleGroupMatch: !Or [!Not [!Equals [!Ref "GoogleGroupMatch", ""]], !Equals [!Ref "SyncMethod", users_groups]]
  SetIgnoreGroups: !Not [!Equals [!Ref "IgnoreGroups", ""]]
  SetIgnoreUsers: !Not [!Equals [!Ref "IgnoreUsers", ""]]
  SetIncludeGroups: !Or [!Not [!Equals [!Ref "IncludeGroups", ""]], !Equals [!Ref "SyncMethod", groups]]
  CreateFunction: !Not [!Equals [!Ref "SyncMethod", "secrets only"]]
  CreateSecrets: !Or [!Equals [!Ref "SyncMethod", "secrets only"], !Equals [!Ref "ValuesOrArns", "value"]]
  LocalGoogleCredentials: !And [!Equals [!Ref "ValuesOrArns", "secrets"], !Equals [ AWS::AccountId, !Select [5, !Split [":", !Ref "GoogleCredentials"]]]]
  LocalGoogleAdminEmail: !And [!Equals [!Ref "ValuesOrArns", "secrets"], !Equals [ AWS::AccountId, !Select [5, !Split [":", !Ref "GoogleAdminEmail"]]]]
  LocalSCIMEndpointUrl: !And [!Equals [!Ref "ValuesOrArns", "secrets"], !Equals [ AWS::AccountId, !Select [5, !Split [":", !Ref "SCIMEndpointUrl"]]]]
  LocalSCIMEndpointAccessToken: !And [!Equals [!Ref "ValuesOrArns", "secrets"], !Equals [ AWS::AccountId, !Select [5, !Split [":", !Ref "SCIMEndpointAccessToken"]]]]
  LocalRegion: !And [!Equals [!Ref "ValuesOrArns", "secrets"], !Equals [ AWS::AccountId, !Select [5, !Split [":", !Ref "Region"]]]]
  LocalIdentityStoreID: !And [!Equals [!Ref "ValuesOrArns", "secrets"], !Equals [ AWS::AccountId, !Select [5, !Split [":", !Ref "IdentityStoreID"]]]]
  CreateOutputs: !And [!Not [!Equals [!Ref "SyncMethod", "secrets only"]], !Equals [!Ref "FunctionName", ""]]

Rules:
  SecretsOnlyValues:
    RuleCondition: !Equals [!Ref "SyncMethod", "secrets only"]
    Assertions:
      - Assert: !Equals [!Ref "ValuesOrArns", "value"]
        AssertDescription: If creating secrets only then values have to be supplied.

Resources:
  SSOSyncFunction:
    Type: AWS::Serverless::Function
    Condition: CreateFunction
    Properties:
      FunctionName: !If [SetFunctionName, !Ref FunctionName, AWS::NoValue]
      Runtime: provided.al2
      Handler: bootstrap
      Architectures:
        - arm64
      Timeout: !Ref TimeOut
      Environment:
        Variables:
          SSOSYNC_LOG_LEVEL: !Ref LogLevel
          SSOSYNC_LOG_FORMAT: !Ref LogFormat
          SSOSYNC_GOOGLE_CREDENTIALS: !If [CreateSecrets, !Ref SecretGoogleCredentials, !Ref GoogleCredentials]
          SSOSYNC_GOOGLE_ADMIN: !If [CreateSecrets, !Ref SecretGoogleAdminEmail, !Ref GoogleAdminEmail]
          SSOSYNC_SCIM_ENDPOINT: !If [CreateSecrets, !Ref SecretSCIMEndpoint, !Ref SCIMEndpointUrl]
          SSOSYNC_SCIM_ACCESS_TOKEN: !If [CreateSecrets, !Ref SecretSCIMAccessToken, !Ref SCIMEndpointAccessToken]
          SSOSYNC_REGION: !If [CreateSecrets, !Ref SecretRegion, !Ref Region]
          SSOSYNC_IDENTITY_STORE_ID: !If [CreateSecrets, !Ref SecretIdentityStoreID, !Ref IdentityStoreID]
          SSOSYNC_USER_MATCH: !If [SetGoogleUserMatch, !Ref GoogleUserMatch, AWS::NoValue]
          SSOSYNC_GROUP_MATCH: !If [SetGoogleGroupMatch, !Ref GoogleGroupMatch, AWS::NoValue]
          SSOSYNC_SYNC_METHOD: !Ref SyncMethod
          SSOSYNC_IGNORE_GROUPS: !If [SetIgnoreGroups, !Ref IgnoreGroups, AWS::NoValue]
          SSOSYNC_IGNORE_USERS: !If [SetIgnoreUsers, !Ref IgnoreUsers, AWS::NoValue]
          SSOSYNC_INCLUDE_GROUPS: !If [SetIncludeGroups, !Ref IncludeGroups, AWS::NoValue]
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: SSMGetParameterPolicy
              Condition: LocalSecrets
              Effect: Allow
              Action:
                - "secretsmanager:Get*"
              Resource:
                - !If [CreateSecrets, !Ref SecretGoogleCredentials, !If [LocalGoogleCredentials, !Ref GoogleCredentials, AWS::NoValue]] 
                - !If [CreateSecrets, !Ref SecretGoogleAdminEmail, !If [LocalGoogleAdminEmail, !Ref GoogleAdminEmail, AWS::NoValue]] 
                - !If [CreateSecrets, !Ref SecretSCIMEndpoint, !If [LocalSCIMEndpointUrl, !Ref SCIMEndpointUrl, AWS::NoValue]] 
                - !If [CreateSecrets, !Ref SecretSCIMAccessToken, !If [LocalSCIMEndpointAccessToken, !Ref SCIMEndpointAccessToken, AWS::NoValue]] 
                - !If [CreateSecrets, !Ref SecretRegion, !If [LocalRegion, !Ref Region, AWS::NoValue]] 
                - !If [CreateSecrets, !Ref SecretIdentityStoreID, !If [LocalIdentityStoreID, !Ref IdentityStoreID, AWS::NoValue]] 
            - Sid: IdentityStoreAccesPolicy
              Effect: Allow
              Action:
                - "identitystore:DeleteUser"
                - "identitystore:CreateGroup"
                - "identitystore:CreateGroupMembership"
                - "identitystore:ListGroups"
                - "identitystore:ListUsers"
                - "identitystore:ListGroupMemberships"
                - "identitystore:IsMemberInGroups"
                - "identitystore:GetGroupMembershipId"
                - "identitystore:DeleteGroupMembership"
                - "identitystore:DeleteGroup"
              Resource:
                - "*"
            - Sid: CodePipelinePolicy
              Effect: Allow
              Action:
                - codepipeline:PutJobSuccessResult
                - codepipeline:PutJobFailureResult
              Resource: "*"
      Events:
        SyncScheduledEvent:
          Type: Schedule
          Name: AWSSyncSchedule
          Properties:
            Enabled: !If [OnSchedule, false, true]
            Schedule: !If [OnSchedule, !Ref ScheduleExpression, "rate(15 minutes)"]

  SecretGoogleCredentials:
    Type: "AWS::SecretsManager::Secret"
    Condition: CreateSecrets
    Properties:
      Name: SSOSyncGoogleCredentials
      SecretString: !Ref GoogleCredentials

  SecretGoogleAdminEmail:
    Type: "AWS::SecretsManager::Secret"
    Condition: CreateSecrets
    Properties:
      Name: SSOSyncGoogleAdminEmail
      SecretString: !Ref GoogleAdminEmail

  SecretSCIMEndpoint: # This can be moved to custom provider
    Type: "AWS::SecretsManager::Secret"
    Condition: CreateSecrets
    Properties:
      Name: SSOSyncSCIMEndpointUrl
      SecretString: !Ref SCIMEndpointUrl

  SecretSCIMAccessToken: # This can be moved to custom provider
    Type: "AWS::SecretsManager::Secret"
    Condition: CreateSecrets
    Properties:
      Name: SSOSyncSCIMAccessToken
      SecretString: !Ref SCIMEndpointAccessToken

  SecretRegion:
    Type: "AWS::SecretsManager::Secret"
    Condition: CreateSecrets
    Properties:
      Name: SSOSyncRegion
      SecretString: !Ref Region

  SecretIdentityStoreID:
    Type: "AWS::SecretsManager::Secret"
    Condition: CreateSecrets
    Properties:
      Name: SSOSyncIdentityStoreID
      SecretString: !Ref IdentityStoreID

Outputs:
  FunctionArn:
    Condition: CreateOutputs
    Description: "The Arn of the deployed lambda function"
    Value: !GetAtt SSOSyncFunction.Arn
    Export:
      Name: SSOSyncFunctionARN
